### ISSUE TITLE
Remote keyboad does not send accented characters typed with Compose

### ISSUE THREAD

**Issue by brettk-git** [GSConnect/gnome-shell-extension-gsconnect#1579]
### Describe the bug

I use the Compose key on my Linux keyboard to enter accented characters (very simple ones, such as e acute).
When I type them into the GSConnect remote keyboard, they do not get sent to my mobile phone.

### Steps to reproduce

STEPS TO REPRODUCE
1. Set up and open the remote keyboard
2. Type [compose] [e] ['] on the Linux keyboard.

### Expected behavior

The character é typed on the phone. But in practice  nothing is typed on the phone.

### GSConnect version

50

### Installed from

GNOME Extensions website

### GNOME Shell version

42.6

### Linux distribution/release

Fedora 36

### Paired device(s)

Galaxy S9

### KDE Connect app version

1.22.2

**Comment by daniellandau** [comment]
This seems similar to https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1572, and I've learned yet another way to input accented characters. Again though, it works fine for me: I can't replicate the issue

**Comment by ferdnyc** [comment]
Yeah, I have to concur with @daniellandau. I'm _heavily_ reliant on the Compose key — it's my go-to for em and en dashes, as well as real • bullets — and while I'm an **infrequent** user of GSConnect's remote input, I just tried it and... **#WorksForMe**:

![image](https://user-images.githubusercontent.com/538020/233211388-3c476c20-bda0-46f5-b418-8e4b71e55841.png)

**Comment by ferdnyc** [comment]
Already regretting not using "soupçon" for that last test word.

**Comment by ferdnyc** [comment]
Note that it's possible that the **input** field in question could have restrictions on what characters are accepted — Android supports a variety of restricted-input modes, with some apps/sites having the ability to automatically pop up a numeric-entry keyboard for fields that only accept digits, etc... So, it could be that the field in question would only accept ASCII, or was doing some sort of input validation that rejected characters not found on a particular keyboard layout.

But when the target will _accept_ composed characters, it seems GSConnect will send them and the KDE Connect Remote Keyboard plugin will deliver them.

**Comment by ferdnyc** [comment]
There is definitely some keyboard weirdness around modifiers, though. For instance, holding <kbd>Super</kbd> and typing <kbd>d</kbd> gets me **two** characters ('dd') per keypress, on both the GSConnect and Android side... whereas holding <kbd>Alt</kbd> and typing <kbd>d</kbd> doesn't show anything on the GSConnect side, but a 'd' is still entered on the Android end! ...But that's all really unrelated to this issue.

**Comment by brettk-git** [comment]
I have just tried again, with a new user starting from scratch, same problem. To be precise: I start with an up to date Fedora 36, I create a new user, log in Gnome (can be on Wayland or on Xorg, this does not matter), I install GSConnect from https://extensions.gnome.org/ in a browser, I configure in the system parameters the right Ctrl key as a Compose key, then I open GSConnect, associate it with my mobile phone, type "hello soup<Compose>c,on", and the phone shows "hello soupon" while the GSConnect text box shows "ç".

**Comment by ferdnyc** [comment]
@brettk-git 
Hmm. It could be an issue with using a modifier as Compose; GSConnect has special processing for the modifier keys. (And as I demonstrated with <kbd>Super</kbd> and <kbd>Alt</kbd>, it's a little... surprising at the best of times.

I use <kbd>Menu</kbd> as my Compose key, personally. Does it work if you configure a **non**-modifier Compose?

**Comment by daniellandau** [comment]
Compose as right ctrl doesn't help me replicate the issue either. Can you share what app you're using on Android side to receive the input?

**Comment by brettk-git** [comment]
I have just tried using "Print screen", which is a non-modifier, as my Compose key. The result is the same.
On the Android side I have tried various apps, just now I tried again with Signal and with K-9 Mail. The  effect is always the same: the accented character gets displayed in the GSConnect text box (as soon as I press the Compose key, the text box starts reacting, even before I press the keys that are to be composed) and does not get sent to the Android device.

**Comment by daniellandau** [comment]
Yeah tried with K-9 mail, works without issues.

**Comment by brettk-git** [comment]
I would like to stress one point: to me it is clear that the problem is independent from the Android side, as the GSConnect text box starts to react as soon as I type the Compose key. In fact, the problem appears even when the KDE Connect keyboard is not active on the Android device. Indeed, the GSConnect text box then shows a message warning the user that the keyboard is not active, nevertheless if I type "abcd[Compose]'efg" in the text box, I do get "é" appearing in the text box (nothing else). (And, as I said, even in this case, the text box starts showing things as soon as I type [Compose].)

**Comment by ferdnyc** [comment]
@brettk-git Fair enough, that does point to a local issue, so I guess the question is why is your GSConnect doing something different from mine and @daniellandau 's?

On _my_ system, using the remote input keyboard with "Generate Support Log" enabled, I see this:

For each regular key I type, there's a log of GSConnect reading the keyval in `vfunc_key_press_event`, e.g.:
```text
[/service/ui/mousepad.js:vfunc_key_press_event:202]: "keyval: 115, mask: 0"
```

That leads immediately to an outgoing `kdeconnect.mousepad.request` packet containing that key:
```json
//[/service/device.js:sendPacket:463]: DEVICE_ID:
{
    "id": 1682255555452,
    "type": "kdeconnect.mousepad.request",
    "body": {
      "alt": false,
      "ctrl": false,
      "shift": false,
      "super": false,
      "sendAck": true,
      "key": "s"
    }
  }
```

Eventually, my phone responds with a `kdeconnect.mousepad.echo` of the same `"key"`.

When I Compose a character, none of the keypresses are captured -- instead, when  I complete the Compose and the Unicode glyph is inserted into the field, `onInsertText` captures the added character:
```text
[/service/ui/mousepad.js:_onInsertText:265]: "insert-text: — (chars 1)"
```

This then leads to a standard `kdeconnect.mousepad.request` packet containing the glyph:
```json
// [/service/device.js:sendPacket:463]: DEVICEID:
{
    "id": 1682255563021,
    "type": "kdeconnect.mousepad.request",
    "body": {
      "alt": false,
      "ctrl": false,
      "shift": false,
      "super": false,
      "sendAck": false,
      "key": "—"
    }
  }
```

...Which is eventually echoed back by the phone.

I guess, if you could supply a capture of what _you_ see in those same circumstances, we can go from there.

**Comment by ferdnyc** [comment]
Oh, one item of note, that the `onInsertText` involvement made me think of: Are you on X11 or Wayland? If you're running X11 still, it's possible the issue is a difference in how the emulated paste-handling is done for Compose.

The other possibility is that this was just fixed more recently than I realize, and it's the fact that you're still on Fedora 36 that's the issue. It may be the case that, "It works in GSConnect 54 (GNOME 43 / Fedora 37), time for an upgrade!" is ultimately the solution here.

**Comment by brettk-git** [comment]
OK, I have now updated to Fedora 38, indeed the problem has disappeared. I guess the bug report can be closed (not fixed, but updating is an easy enough fix). To answer @ferdnyc let me add that the problem was occurring with both X11 and Wayland. Also let me point out that after the update, now that the problem has gone, the whole behaviour of the GSConnect keyboard text box is quite different: the non-accented characters that I type on the computer do appear in the text box (while previously they were sent to the Android device but would not appear in the text box).

**Comment by ferdnyc** [comment]
> Also let me point out that after the update, now that the problem has gone, the whole behaviour of the GSConnect keyboard text box is quite different: the non-accented characters that I type on the computer do appear in the text box (while previously they were sent to the Android device but would not appear in the text box).

Yeah, the KDE Connect Android app now sends back `echo` packets that we're using to display the input characters, so that what you   see locally matches the remote. (There can be a bit of a delay at times, because of that, but overall the experience is cleaner.

Since this works with `v54` in F37 and with the current `v55` in F38, and since F36 will be reaching EOL in a month's time, closing this as working in current releases.
